/**
 * Tool argument types for checked access auth stubs (generated by db2ai — do not edit).
 */
export type InvokeOptions = Record<string, unknown>;

export type CheckedHostContext = {
    credential: string;
    jwt?: Record<string, unknown>;
};
