import type { Model } from 'db-2-ai-dsl-language';
import { getAccessKind, isSqlQuery } from 'db-2-ai-dsl-language';
import {
    ensureCheckedAuthStubsFromSource,
    parameterCheckExportName,
    renderParameterCheckerImports,
    renderParameterCheckersMap,
    type AccessKind
} from '@core2ai/core/codegen';

export type ToolAccess = AccessKind;

export function listCheckedToolNames(model: Model): string[] {
    const names: string[] = [];
    for (const entry of model.entries) {
        if (!isSqlQuery(entry)) {
            continue;
        }
        if (getAccessKind(entry) === 'checked' && entry.toolName?.trim()) {
            names.push(entry.toolName.trim());
        }
    }
    return names;
}

export { parameterCheckExportName, renderParameterCheckerImports, renderParameterCheckersMap };

export const AUTH_INVOKE_OPTIONS_BASENAME = 'db2ai-invoke-options';

export function renderAuthInvokeOptionsTypeFile(): string {
    return `/**
 * Tool argument types for checked access auth stubs (generated by db2ai — do not edit).
 */
export type InvokeOptions = Record<string, unknown>;

export type CheckedHostContext = {
    credential: string;
    jwt?: Record<string, unknown>;
};
`;
}

export async function ensureCheckedAuthStubs(source: string, model: Model): Promise<Map<string, string>> {
    return ensureCheckedAuthStubsFromSource(
        source,
        listCheckedToolNames(model),
        AUTH_INVOKE_OPTIONS_BASENAME,
        renderAuthInvokeOptionsTypeFile()
    );
}

export function renderInvokeCredentialAndParameterCheck(hasAuth: boolean, hasChecked: boolean): string {
    const credentialGuard = hasAuth
        ? `
    if (toolMeta.access !== 'public') {
        if (!host.credential || !String(host.credential).trim()) {
            throw new Error(
                'Missing host credential. Pass --auth-env on mcp-serve.mjs and set the variable (re-read on every tool call).'
            );
        }
    }`
        : '';

    const checkedAccessBlock = hasChecked
        ? `
    if (toolMeta.access === 'checked') {
        const check = parameterCheckers[toolName];
        if (typeof check !== 'function') {
            throw new Error('No parameter checker for checked tool: ' + toolName);
        }
        optionsResolved = await Promise.resolve(
            check(options, {
                credential: String(host.credential).trim(),
                jwt: host.jwt
            })
        );
    }`
        : '';

    const optionsResolvedDecl = hasChecked ? '\n    let optionsResolved = options;' : '';

    return `${credentialGuard}${optionsResolvedDecl}${checkedAccessBlock}`;
}
