import type { Model } from 'db-2-ai-dsl-language';
import { getAccessKind, isSqlQuery } from 'db-2-ai-dsl-language';
import { compileAuthStubSources, parameterCheckExportName, type AccessKind } from '@core2ai/core/codegen';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { resolveBootstrapProjectRootFromSource } from '@core2ai/core/codegen';

export type ToolAccess = AccessKind;

export function listCheckedToolNames(model: Model): string[] {
    const names: string[] = [];
    for (const entry of model.entries) {
        if (!isSqlQuery(entry)) {
            continue;
        }
        if (getAccessKind(entry) === 'checked' && entry.toolName?.trim()) {
            names.push(entry.toolName.trim());
        }
    }
    return names;
}

export { parameterCheckExportName };

export const AUTH_INVOKE_OPTIONS_BASENAME = 'db2ai-invoke-options';

export function renderAuthInvokeOptionsTypeFile(): string {
    return `/**
 * Tool argument types for checked access auth stubs (generated by db2ai — do not edit).
 */
export type InvokeOptions = Record<string, unknown>;

export type CheckedHostContext = {
    credential: string;
    jwt?: Record<string, unknown>;
};
`;
}

function writeAuthInvokeOptionsTypeFile(authDir: string): void {
    const typesPath = path.join(authDir, `${AUTH_INVOKE_OPTIONS_BASENAME}.ts`);
    fs.writeFileSync(typesPath, renderAuthInvokeOptionsTypeFile(), 'utf-8');
}

function renderStubFileContent(toolName: string): string {
    const fn = parameterCheckExportName(toolName);
    return `/**
 * Checked access parameter check for "${toolName}" (write-once — implement ${fn}).
 */
import type { InvokeOptions, CheckedHostContext } from './${AUTH_INVOKE_OPTIONS_BASENAME}.js';

export function ${fn}(options: InvokeOptions, host: CheckedHostContext): InvokeOptions {
    void options;
    void host;
    throw new Error('Implement ${fn} in src/auth/${toolName}.ts');
}
`;
}

export async function ensureCheckedAuthStubs(source: string, model: Model): Promise<Map<string, string>> {
    const projectRoot = resolveBootstrapProjectRootFromSource(source);
    const authDir = path.join(projectRoot, 'src', 'auth');
    if (!fs.existsSync(authDir)) {
        fs.mkdirSync(authDir, { recursive: true });
    }

    const checked = listCheckedToolNames(model);
    if (checked.length === 0) {
        return new Map();
    }

    writeAuthInvokeOptionsTypeFile(authDir);

    const importPaths = new Map<string, string>();
    for (const toolName of checked) {
        const tsPath = path.join(authDir, `${toolName}.ts`);
        const mjsPath = path.join(authDir, `${toolName}.mjs`);
        if (!fs.existsSync(tsPath)) {
            fs.writeFileSync(tsPath, renderStubFileContent(toolName), 'utf-8');
        }
        importPaths.set(toolName, mjsPath);
    }

    await compileAuthStubSources(authDir);
    return importPaths;
}

export function renderParameterCheckerImports(
    tsPath: string,
    stubPaths: Map<string, string>,
    typescript: boolean
): string {
    const lines: string[] = [];
    for (const [toolName, absStub] of stubPaths) {
        const absImport = typescript ? path.resolve(path.dirname(absStub), `${toolName}.ts`) : path.resolve(absStub);
        let rel = path
            .relative(path.dirname(path.resolve(tsPath)), absImport)
            .split(path.sep)
            .join('/');
        if (!rel.startsWith('.')) {
            rel = `./${rel}`;
        }
        if (typescript) {
            rel = rel.replace(/\.ts$/, '.js');
        }
        const fn = parameterCheckExportName(toolName);
        lines.push(`import { ${fn} } from '${rel}';`);
    }
    return lines.join('\n');
}

export function renderParameterCheckersMap(stubPaths: Map<string, string>, typescript = false): string {
    if (stubPaths.size === 0) {
        return typescript ? 'const parameterCheckers: Record<string, never> = {};' : 'const parameterCheckers = {};';
    }
    const typeAnnotation = typescript
        ? ': Record<string, (options: InvokeOptions, host: CheckedHostContext) => InvokeOptions | Promise<InvokeOptions>>'
        : '';
    const entries = [...stubPaths.keys()].map((toolName) => {
        const fn = parameterCheckExportName(toolName);
        return `    ${JSON.stringify(toolName)}: ${fn}`;
    });
    return `const parameterCheckers${typeAnnotation} = {\n${entries.join(',\n')}\n};`;
}

export function renderInvokeCredentialAndParameterCheck(hasAuth: boolean, hasChecked: boolean): string {
    const credentialGuard = hasAuth
        ? `
    if (toolMeta.access !== 'public') {
        if (!host.credential || !String(host.credential).trim()) {
            throw new Error(
                'Missing host credential. Pass --auth-env on mcp-serve.mjs and set the variable (re-read on every tool call).'
            );
        }
    }`
        : '';

    const checkedAccessBlock = hasChecked
        ? `
    if (toolMeta.access === 'checked') {
        const check = parameterCheckers[toolName];
        if (typeof check !== 'function') {
            throw new Error('No parameter checker for checked tool: ' + toolName);
        }
        optionsResolved = await Promise.resolve(
            check(options, {
                credential: String(host.credential).trim(),
                jwt: host.jwt
            })
        );
    }`
        : '';

    const optionsResolvedDecl = hasChecked ? '\n    let optionsResolved = options;' : '';

    return `${credentialGuard}${optionsResolvedDecl}${checkedAccessBlock}`;
}
